apiVersion: apps/v1
kind: Deployment
metadata:
  name: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b-depl
  labels:
    app: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b
  template:
    metadata:
      labels:
        app: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b
    spec:
      containers:
        - name: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8099

