apiVersion: v1
kind: Service
metadata:
  name: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b-srv
spec:
  selector:
    app: use-auth-apis-coll-5c68353ea86a4a848ab6c989ed13a33b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8099
  type: LoadBalancer